### ISSUE TITLE
The Serial page Usagle Baud Rate table needs to be expanded to include T4.x boards.

### ISSUE THREAD

**Issue by KurtE** [PaulStoffregen/Website_Updates#26]
https://www.pjrc.com/teensy/td_uart.html

As mentioned in the forum: https://forum.pjrc.com/threads/69839-Recommended-baud-rate-on-Teensy-4-1?p=302776#post302776

**Comment by KurtE** [comment]
Done I believe

**Comment by bhelterline** [comment]
No, the page has not been updated.  If you go to the page and scroll down 2/3 of the way, this is the part that needs updating:

**Serial1.begin(baud, format)**
Initialize the serial object with a baud rate and data format. Supported only on Teensy LC, 3.0, 3.1, 3.2, 3.5, 3.6.
[table of format constants]


It needs to say "Supported only on Teensy LC, 3.X, 4,X" or something similar
