### ISSUE TITLE
Confusion over "reset" button perpetuated by website.

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [PaulStoffregen/Website_Updates#27]
Issues such as https://forum.pjrc.com/threads/69801-Very-surprising-behaviour-of-reset-button are a regular feature of the forum, and aren't helped by pages like https://www.pjrc.com/teensy/loader_cli.html which mentions reset no fewer than 5 times. Looks like a trawl over the page sources looking to see where "reset [button]" should be replaced by "program [button]" would be useful, though you're never going to get _everyone_ to RTFWS.

**Comment by PaulStoffregen** [comment]
I've made some updates on that page.  Hopefully better now?

Much of this was written in the days of Teensy 2.0 when it was called Reset rather than Program.  Probably still more places on the website in need of updates...

**Comment by PaulStoffregen** [comment]
Going to consider this issue solved, even though probably more places exist elsewhere on the website.

Please feel free to reopen this issue with any specific locations still in need of updates.
