### ISSUE TITLE
Documentation for AudioEffectDelayExternal is wrong (I think)

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [PaulStoffregen/Website_Updates#28]
Seems to have been copy / pasted from AudioEffectDelay, and both state that using disable(channel) will free up memory if it's the channel with the longest delay. I _think_ this is only true for AudioEffectDelay, because it uses audio blocks, but AudioEffectDelayExternal  allocates its (external) memory on initialisation and never changes it.

Oh, and "accommodate" has two 'm's

**Comment by PaulStoffregen** [comment]
Fixed with https://github.com/PaulStoffregen/Audio/commit/4fe12146b2343a385d9d341d786f6d61b99c7c7c
