### ISSUE TITLE
Audio Shield BCLK speed documentation wrong

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [PaulStoffregen/Website_Updates#30]
At least for Teensy 4, I haven't tested Teensy 3. https://www.pjrc.com/store/teensy3_audio.html says BCLK is 1.41MHz but it's actually 2.82MHz. The table of "Signals to Teensy" has both speeds documented, but the top paragraph does not, neither does the table explain when each frequency is observed (different Teensys? different libraries?).

It would possibly be helpful to hardware designers to know the output format chosen for the various I²S objects - for T4.x looks like a 16-bit word left justified in a 32-bit field, offset by one clock from BCLK.

**Comment by h4yn0nnym0u5e** [comment]
...also, it's not _completely_ clear which pins need connecting for full functionality. Fairly sure it's 3.3V, _both_ (?) Gnd pins, the five I²S pins and the two I²C pins.

**Comment by PaulStoffregen** [comment]
I updated both descriptions to say 1.41 or 2.82 MHz.  Description links to Wikipedia for I2S format and Design Tool for precise detail about which features use each clock speed.

Added a "Required For" to the signals table.  Hopefully that clears up all the issues?

**Comment by h4yn0nnym0u5e** [comment]
Looks good to me
