### ISSUE TITLE
Website says Teensy 4.0 4.1 4.x does not support AnalogWriteFrequency 

### ISSUE THREAD

**Issue by KurtE** [PaulStoffregen/Website_Updates#31]
https://forum.pjrc.com/threads/70529-Website-says-Teensy-4-0-4-1-4-x-does-not-support-AnalogWriteFrequency

Hi All!
I found several folks in the forum using AnalogWriteFrequency on Teensy 4.x, but the 

https://www.pjrc.com/teensy/td_pulse.html#frequency says it is only for the Teenst LC and 3.x Boards.

"Teensy LC & 3.x support the analogWriteFrequency(pin, frequency) function to easily configure the PWM."

Am I misunderstanding things? It seems perhaps the page was not updates fully for the Teensy 4.x. 

Thank you for your work!

**Comment by KurtE** [comment]
I believe he is referring to the statement: Teensy LC & 3.x support the analogWriteFrequency(pin, frequency) function to easily configure the PWM. 

Right after the table that shows all of the pins

**Comment by Robbbb** [comment]
Thanks @KurtE! that is exactly what I was referring to.

**Comment by PaulStoffregen** [comment]
Updated text to "Teensy LC, 3.x, 4.x support the analogWriteFrequency(pin, frequency) function to easily configure the PWM."
