### ISSUE TITLE
Teensy LC page - Issue with AREF documentation plus schematic issue on VUSB

### ISSUE THREAD

**Issue by KurtE** [PaulStoffregen/Website_Updates#32]
User mkoch  created two threads on this.

https://forum.pjrc.com/threads/70780-Teensy-LC-Bug-in-documentation
https://forum.pjrc.com/threads/70774-Teensy-LC-Bug-in-schematic

One is talking about VUSB pad, pin and Polyfuse

The other is talking about AREF pin and does it actually have a resistor on the Teensy?

"The AREF pin is used to set the analog input range. By default, AREF is 3.3V due to a resistor. External shunt-type reference chips may be connected for lower reference voltage."

Is there a resistor or is this trying to say something like the analogRead will default to the internal voltage reference....

**Comment by PaulStoffregen** [comment]
Teensy LC page updated.

**Comment by mkoch44** [comment]
What about the bug in the schematic?

**Comment by PaulStoffregen** [comment]
Done
