### ISSUE TITLE
AudioConnection documentation needs an update

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [PaulStoffregen/Website_Updates#33]
See https://www.pjrc.com/teensy/td_libs_AudioConnection.html. It states "AudioConnection objects do not have any functions", which is no longer true since dynamic connections (from TD 1.57 onwards) allow disconnect() and connect() to re-patch the design.

**Comment by PaulStoffregen** [comment]
Updated.  Does the new info look ok?

**Comment by h4yn0nnym0u5e** [comment]
Looks good to me
