### ISSUE TITLE
Teensy loader page(s) downloads version of teensy.exe is out of date and does not support all boards

### ISSUE THREAD

**Issue by KurtE** [PaulStoffregen/Website_Updates#34]
https://www.pjrc.com/teensy/loader.html 
Page, if you go to the Windows Page:
https://www.pjrc.com/teensy/loader_win10.html
And click the download, it will download the teensy.exe from Teensyduino 1.52 which does not support Micromod.
Have not checked the MAC or linux page but would guess similar.

(Might also update pages to reflect more current versions of OS) and more recent boards. 
Windows page talks about Vista.
```
Using The Teensy Loader on Windows Vista
Update: [Teensy 3.0 is supported by Teensyduino](https://www.pjrc.com/teensy/td_download.html). After installation, Teensy Loader is in hardware/tools. It is run automatically when using Verify or Upload within the Arduino software. This version on this web page has not been updated for Teensy 3.0. Please insta ll Teensyduino to use Teensy 3.0.

```
Mac - Wonder if it works on newer OS?

Was reported on forum in thread:
https://forum.pjrc.com/threads/71670-Out-of-date-Windows-Loader-on-pjrc-com

**Comment by PaulStoffregen** [comment]
Updated.
