### ISSUE TITLE
2021 loader linked form PJRC websites

### ISSUE THREAD

**Issue by Defragster** [PaulStoffregen/Website_Updates#40]
See thread: https://forum.pjrc.com/threads/73558-Locked-Teensy-quot-bricks-quot?p=331895&viewfull=1#post331895

Page linked there is : https://www.pjrc.com/teensy/loader.html

Goes to WINDOWS and downloaded exe has digital signature showing Dec 22, 2021

This will FAIL use for locked Teensy

**Comment by PaulStoffregen** [comment]
updated
